application: gc-api-test
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/admin/delete-tokens
  script: api.app
  login: admin

- url: /api/admin/init-db
  script: api.app
  login: admin

- url: /api/.*
  script: api.app

libraries:
- name: webapp2
  version: "2.5.2"
